from.accounts import *
from.about import *
from.experience import *
from.education import *
from.language_skills import *
from.portfolio import *
from.recommendations import *
from.social_media import *
from.seo_tags import *
