# Generated by Django 4.1 on 2022-09-05 11:15

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='', max_length=100)),
                ('Designation', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=100)),
                ('areaofResearch', models.CharField(default='', max_length=100)),
                ('previousJob', models.CharField(default='', max_length=100)),
                ('School', models.CharField(default='', max_length=100)),
                ('Birthday', models.CharField(default='', max_length=100)),
                ('meritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='', max_length=100)),
                ('Nationality', models.CharField(default='', max_length=100)),
                ('Skype', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(max_length=100, unique=True)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('description', models.TextField(default='')),
                ('resume', models.FileField(default='', upload_to='Resume')),
                ('profile', models.ImageField(default='', upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('School', models.CharField(default='', max_length=100)),
                ('StudyArea', models.CharField(default='', max_length=100)),
                ('From', models.CharField(default='', max_length=100)),
                ('To', models.CharField(default='', max_length=100)),
                ('Icon', models.ImageField(default='', upload_to='Education')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Designation', models.CharField(default='', max_length=100)),
                ('From', models.CharField(default='', max_length=100)),
                ('To', models.CharField(default='', max_length=100)),
                ('Company', models.CharField(default='', max_length=100)),
                ('Street', models.CharField(default='', max_length=100)),
                ('Description', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LangSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(default='', max_length=100)),
                ('expert1', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill2', models.CharField(default='', max_length=100)),
                ('expert2', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill3', models.CharField(default='', max_length=100)),
                ('expert3', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill4', models.CharField(default='', max_length=100)),
                ('expert4', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill5', models.CharField(default='', max_length=100)),
                ('expert5', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill6', models.CharField(default='', max_length=100)),
                ('expert6', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill7', models.CharField(default='', max_length=100)),
                ('expert7', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('skill8', models.CharField(default='', max_length=100)),
                ('expert8', models.CharField(choices=[('10%', '10%'), ('30%', '30%'), ('50%', '50%'), ('70%', '70%'), ('90%', '90%'), ('100%', '100%')], default='', max_length=100)),
                ('lang1', models.CharField(default='', max_length=100)),
                ('str1', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=100)),
                ('lang2', models.CharField(default='', max_length=100)),
                ('str2', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=100)),
                ('lang3', models.CharField(default='', max_length=100)),
                ('str3', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='', max_length=100)),
                ('Icon1', models.ImageField(default='', upload_to='LangSkill/langIcons')),
                ('Icon2', models.ImageField(default='', upload_to='LangSkill/langIcons')),
                ('Icon3', models.ImageField(default='', upload_to='LangSkill/langIcons')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(default='', max_length=300)),
                ('thumbnail', models.ImageField(default='', upload_to='Portfolio/Thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('heading', models.CharField(default='', max_length=5000)),
                ('tags', models.CharField(default='', max_length=5000)),
                ('quote', models.CharField(default='', max_length=3000)),
                ('quote_by', models.CharField(default='', max_length=500)),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('Icon', models.ImageField(default='', upload_to='Blog/Icons')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(default='', max_length=100)),
                ('designation', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
