# Generated by Django 4.1 on 2022-09-05 12:07

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0003_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='userBlog',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('heading', models.CharField(default='', max_length=255)),
                ('tags', models.CharField(default='', max_length=255)),
                ('quote', models.CharField(default='', max_length=255)),
                ('quote_by', models.CharField(default='', max_length=255)),
                ('description', ckeditor.fields.RichTextField(default='')),
                ('Icon', models.ImageField(default='', upload_to='Blog/Icons')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 5, 12, 7, 50, 520967, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
