# Generated by Django 4.1 on 2022-09-06 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminPanel', '0004_userblog_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 7, 51, 14, 145522, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='blog_Review',
            fields=[
                ('sNo', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('comment', models.TextField(default='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminPanel.blog_review')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminPanel.userblog')),
            ],
        ),
    ]
