from .about import *
from .experience import *
from .portfolio import *
from .education import *
from .language_skills import *
from .recommendations import *
from .social_media import *
from .blog import *
from .say_hello import *
from .piaic import *
from .seo_tags import *