from .accounts import *
from .home import *
from .seo_tags import *
from .about import *
from .experience import *
from .education import *
from .skills_language import *
from .portfolio import *
from .recommendations import *
from .socila_media import *
from .blog import *
from .piaic import *
from .view_messages import *
from .update import *
from .delete import *
